os: linux
dist: trusty

matrix:
  include:

    - name: "Python Tests using pytest"
      language: python
      python:
        - 3.5.2
      # install dependencies
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov-report term-missing --cov=substitution_ciphers
        - codeclimate-test-reporter --file .coverage
      addons:
        code_climate:
          repo_token:
            secure: a9c84c370277a441949547075f54d1bd9335f313e35e189104909c598dfed072

    - name: "JavaScript Tests using jasmine"
      language: node_js
      os: linux
      dist: trusty
      node_js:
        - "node"
      install:
        - yarn add jasmine
      before_script:
        - cd book_ciphers
      script:
        - node ./tests/spec_runner.js
